import {
  ForkKnifeIcon,
  HamburgerIcon,
  PizzaIcon,
  BowlFoodIcon,
  CookingPotIcon,
  FishIcon,
  FishSimpleIcon,
  FireIcon,
  EggIcon,
  EggCrackIcon,
  BreadIcon,
  CarrotIcon,
  IceCreamIcon,
  CakeIcon,
  CookieIcon,
  CoffeeIcon,
  CoffeeBeanIcon,
  TeaBagIcon,
  WineIcon,
  BeerBottleIcon,
  BeerSteinIcon,
  PintGlassIcon,
  MartiniIcon,
  ChampagneIcon,
  DropIcon,
  BowlSteamIcon,
  PopcornIcon,
  CherriesIcon,
  AvocadoIcon,
  CheeseIcon,
  NutIcon,
  OrangeIcon,
  OrangeSliceIcon,
  PepperIcon,
  ShrimpIcon,
  JarIcon,
  BasketIcon,
  StarIcon,
  FlaskIcon,
  SkullIcon,
  LeafIcon,
  KnifeIcon,
  TrayIcon,
  GiftIcon,
  CowIcon,
  type Icon,
} from '@phosphor-icons/react'

// Set curado de íconos de comida/bebida (no todo el catálogo de Phosphor,
// sería inmanejable en un picker) — el admin elige uno por categoría en el
// modal de Gestionar Categorías, para mostrarlo en las cards del selector
// de productos en vez de solo texto.
export const CATEGORY_ICONS: Record<string, Icon> = {
  fork_knife: ForkKnifeIcon,
  hamburger: HamburgerIcon,
  pizza: PizzaIcon,
  bowl_food: BowlFoodIcon,
  cooking_pot: CookingPotIcon,
  fish: FishIcon,
  fish_simple: FishSimpleIcon,
  fire: FireIcon,
  egg: EggIcon,
  egg_crack: EggCrackIcon,
  bread: BreadIcon,
  carrot: CarrotIcon,
  ice_cream: IceCreamIcon,
  cake: CakeIcon,
  cookie: CookieIcon,
  coffee: CoffeeIcon,
  coffee_bean: CoffeeBeanIcon,
  tea_bag: TeaBagIcon,
  wine: WineIcon,
  beer: BeerBottleIcon,
  beer_stein: BeerSteinIcon,
  pint_glass: PintGlassIcon,
  martini: MartiniIcon,
  champagne: ChampagneIcon,
  drop: DropIcon,
  bowl_steam: BowlSteamIcon,
  popcorn: PopcornIcon,
  cherries: CherriesIcon,
  avocado: AvocadoIcon,
  cheese: CheeseIcon,
  nut: NutIcon,
  orange: OrangeIcon,
  orange_slice: OrangeSliceIcon,
  pepper: PepperIcon,
  shrimp: ShrimpIcon,
  jar: JarIcon,
  basket: BasketIcon,
  star: StarIcon,
  flask: FlaskIcon,
  skull: SkullIcon,
  leaf: LeafIcon,
  knife: KnifeIcon,
  tray: TrayIcon,
  gift: GiftIcon,
  cow: CowIcon,
}

export type CategoryIconKey = keyof typeof CATEGORY_ICONS

export function getCategoryIcon(key: string | null | undefined): Icon | null {
  if (!key) return null
  return CATEGORY_ICONS[key] ?? null
}
