import {
  ForkKnife,
  Hamburger,
  Pizza,
  BowlFood,
  CookingPot,
  Fish,
  FishSimple,
  Fire,
  Egg,
  EggCrack,
  Bread,
  Carrot,
  IceCream,
  Cake,
  Cookie,
  Coffee,
  CoffeeBean,
  TeaBag,
  Wine,
  BeerBottle,
  BeerStein,
  PintGlass,
  Martini,
  Champagne,
  Drop,
  BowlSteam,
  Popcorn,
  Cherries,
  Avocado,
  Cheese,
  Nut,
  Orange,
  OrangeSlice,
  Pepper,
  Shrimp,
  Jar,
  Basket,
  Star,
  Flask,
  Skull,
  Leaf,
  Knife,
  Tray,
  Gift,
  Cow,
  type Icon,
} from '@phosphor-icons/react'

// Set curado de íconos de comida/bebida (no todo el catálogo de Phosphor,
// sería inmanejable en un picker) — el admin elige uno por categoría en el
// modal de Gestionar Categorías, para mostrarlo en las cards del selector
// de productos en vez de solo texto.
export const CATEGORY_ICONS: Record<string, Icon> = {
  fork_knife: ForkKnife,
  hamburger: Hamburger,
  pizza: Pizza,
  bowl_food: BowlFood,
  cooking_pot: CookingPot,
  fish: Fish,
  fish_simple: FishSimple,
  fire: Fire,
  egg: Egg,
  egg_crack: EggCrack,
  bread: Bread,
  carrot: Carrot,
  ice_cream: IceCream,
  cake: Cake,
  cookie: Cookie,
  coffee: Coffee,
  coffee_bean: CoffeeBean,
  tea_bag: TeaBag,
  wine: Wine,
  beer: BeerBottle,
  beer_stein: BeerStein,
  pint_glass: PintGlass,
  martini: Martini,
  champagne: Champagne,
  drop: Drop,
  bowl_steam: BowlSteam,
  popcorn: Popcorn,
  cherries: Cherries,
  avocado: Avocado,
  cheese: Cheese,
  nut: Nut,
  orange: Orange,
  orange_slice: OrangeSlice,
  pepper: Pepper,
  shrimp: Shrimp,
  jar: Jar,
  basket: Basket,
  star: Star,
  flask: Flask,
  skull: Skull,
  leaf: Leaf,
  knife: Knife,
  tray: Tray,
  gift: Gift,
  cow: Cow,
}

export type CategoryIconKey = keyof typeof CATEGORY_ICONS

export function getCategoryIcon(key: string | null | undefined): Icon | null {
  if (!key) return null
  return CATEGORY_ICONS[key] ?? null
}
